spring:
  application:
    name: aws-s3
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: plinqer-dev
    region:
      static: ap-northeast-2
    stack:
      auto: false
